### ISSUE TITLE
XD.

### ISSUE THREAD

**Issue by ghost** [6vz/editsyf#1]
ty przyjebany jesteś XDD
kolejny kurwa leak frontendu ja pierdole XD

jebać editbota, juica i olava ;)

**Comment by legacy6vz** [comment]
to nie jest leak, strone poprostu hostuje na github pages, domena editbot,online należy do mnie

**Comment by ghost** [comment]
a dobra bo @kacperrrooo pisał że to leak frontendu a mi się nie chciało sprawdzać dokładniej xd
to dobrze że przynajmniej nie jesteś aż tak zjebany jak hazuki

**Comment by legacy6vz** [comment]
> 
> 
> a dobra bo @kacperrrooo pisał że to leak frontendu a mi się nie chciało sprawdzać dokładniej xd
> to dobrze że przynajmniej nie jesteś aż tak zjebany jak hazuki

tak to prawda, ale usunałem go na prośbę właściciela ;)
zrobiłem głupio i o tym wiem :/

**Comment by ghost** [comment]
aok
"To dobrze"
